Repository Alefowl/welcome, pull requests merged in 2024-01, with the labels that each got.

#1 1-path
  README.md
  reports/1st day/stakap.txt
  reports/2nd day/stakap.txt
  reports/3d day/stakap.txt
  reports/4th and 5th days/stakap.txt
  reports/6th day/stakap.txt
  reports/7th and 8th days/stakap.txt
  reports/9th and 10th days/stakap.txt
Labels: Ready to merge

#3 2-rules
  README.md
  help/add-book.md
  help/add-report.md
Labels: Review, Work in progress

#4 3-almost
  README.md
Labels: Review

#14 6-lasfront
  reports/6th day/lasfront.md
Labels: Ready to merge

#13 ZazAnna
  reports/1st day/ZazAnna
Labels: Ready to merge

#16 4-labels
  help/add-report.md
Labels: Ready to merge

#24 2nd ElizavetaKhmel
  reports/2nd day/ElizavetaKhmel.txt
Labels: Ready to merge

#29 3 day
  reports/3d day/hurrah1996.txt
Labels: Ready to merge
